export const BASE_URL = 'http://localhost:5000'
export const PRODUCT_URL = '/api/products'
export const USER_URL = '/api/user'
export const ORDERS_URL = '/api/orders'
export const PAYPAL_URL = '/api/paypal'
